config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # list all restaurants
  get "tasks", to: "tasks#index"
  #create new restaurant
  post "tasks", to: "tasks#create"
  get "tasks/new", to: "tasks#new"
  # see one restaurant
  get "tasks/:id", to: "tasks#show", as: :task
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  #update
  patch "tasks/:id", to: "tasks#update", as: :update_task
  delete "tasks/:id", to: "tasks#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<h1>New Task</h1>

<h3>Title</h3>
<%= form_for(@task) do |f| %>
<!--   <%= f.label :title %> -->
  <%= f.text_field :title %>
<h4>Details</h4>
 <!--  <%= f.label :details %> -->
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.text_field :completed %>

 <p> <%= f.submit %> </p>
<% end %>

<p> --- </p>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<h3>Title</h3>
<%= form_for(@task) do |f| %>
<!--   <%= f.label :title %> -->
  <%= f.text_field :title %>
<h4>Details</h4>
 <!--  <%= f.label :details %> -->
  <%= f.text_field :details %>

 <p>
 <%= f.label :completed %>
<%= f.check_box :completed %> </p>

 <p> <%= f.submit %> </p>
<% end %>

<p> --- </p>

<%=link_to "Back to list", tasks_path%>

app/views/tasks/index.html.erb
<h1> My Tasks </h1>
<%@tasks.each do |task|%>
<% if task.completed  %>
<p> [x] <%=link_to task.title, task_path(task)%> </p>
<% else %>
<p> [ ] <%=link_to task.title, task_path(task)%> </p>
<% end %>
<% end %>

<%=link_to "+ Add a new task", tasks_new_path%>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>
<%=link_to "Back to list", tasks_path%>

app/views/tasks/show.html.erb
<h1><%= @task.title %> </h1>
<p> <%=  @task.details %> </p>
<% if @task.completed  %>
<p> [x] This task is already completed. </p>
<% else %>
<p> [ ] This task is not completed yet. </p>
<% end %>

<%= link_to "edit", edit_task_path(@task) %>
<%= link_to "Delete", task_path(@task),
      method: :delete,
      data: { confirm: "Are you sure?" } %>



<%=link_to "Back to list", tasks_path%>